In [1]:
## Carga do Dataset

import pandas as pd 
import numpy as np 

dataset = pd.read_csv("Datasets\AraraAzul_Class_20201129.csv", delimiter=";", encoding="utf-8") # Utilização do dataset classificado manualmente com os Tweets
dataset.head()

Tweet  ... Classification
0  Minha família é louca demais kkk\nMeu tio perg...  ...             -1
1  Se é azul e fala, só pode ser uma arara https:...  ...              0
2  E ontem o cara me aparece com uma arara azul n...  ...             -1
3  @hallwayghost KAKAKKAKA a arara azul era de um...  ...             -1
4  @twentyhalpert eu moro interior to acostumada ...  ...              0

[5 rows x 10 columns]

In [2]:
dataset['Classification'] = dataset['Classification'].fillna(0)
dataset["Classification"] = dataset["Classification"].astype(int)

In [3]:
dataset.head()

Tweet  ... Classification
0  Minha família é louca demais kkk\nMeu tio perg...  ...             -1
1  Se é azul e fala, só pode ser uma arara https:...  ...              0
2  E ontem o cara me aparece com uma arara azul n...  ...             -1
3  @hallwayghost KAKAKKAKA a arara azul era de um...  ...             -1
4  @twentyhalpert eu moro interior to acostumada ...  ...              0

[5 rows x 10 columns]

In [9]:
import gensim
from gensim import corpora

# Importando os Embeddings e transformando num array


tf_idf_emb = corpora.MmCorpus('Embeddings\TF_IDF\matriz_tfidf.mm')
tf_idf_emb = gensim.matutils.corpus2csc(tf_idf_emb)
tf_idf_emb = tf_idf_emb.T.toarray()

In [10]:
print(tf_idf_emb)

[[0.00255403 0.00229355 0.25477148 ... 0.         0.         0.        ]
 [0.00765648 0.00687561 0.         ... 0.         0.         0.        ]
 [0.00388055 0.00348478 0.         ... 0.         0.         0.        ]
 ...
 [0.00369792 0.00332078 0.         ... 0.         0.         0.        ]
 [0.00224915 0.00201976 0.         ... 0.         0.         0.        ]
 [0.00277388 0.00249097 0.         ... 0.34647662 0.34647662 0.34647662]]


In [11]:
# Dividindo o Dataset em treino e test (TF-IDF)


X = tf_idf_emb #Embeddings
y = dataset.iloc[:, -1].values # Obtem o valor da coluna "Classification" do dataset

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [16]:
## Treino NAIVE BAYES model

from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [18]:
#Testes e Resultados Naive

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 2  2  0]
 [ 4 29  4]
 [ 0  4  2]]


0.7021276595744681

In [37]:
# Regressão Logistica

from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0, penalty="l2", tol=0.0001)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [38]:
y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 0  4  0]
 [ 0 37  0]
 [ 0  6  0]]


0.7872340425531915

In [39]:
## Kernel SVM

from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(random_state=0)

In [40]:
y_pred_SVC = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_SVC)
print(cm)
accuracy_score(y_test, y_pred_SVC)

[[ 0  4  0]
 [ 0 37  0]
 [ 0  6  0]]


0.7872340425531915